-- MySQL Script generated by MySQL Workbench
-- 05/27/17 14:39:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema FastFoodBD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FastFoodBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FastFoodBD` DEFAULT CHARACTER SET utf8 ;
USE `FastFoodBD` ;

-- -----------------------------------------------------
-- Table `FastFoodBD`.`Turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FastFoodBD`.`Turno` (
  `id_turno` INT NOT NULL AUTO_INCREMENT,
  `nombre_turno` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_turno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FastFoodBD`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FastFoodBD`.`Cargo` (
  `idCargo` INT NOT NULL AUTO_INCREMENT,
  `nombre_cargo` VARCHAR(45) NOT NULL,
  `descripcion_cargo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FastFoodBD`.`Personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FastFoodBD`.`Personal` (
  `idPersonal` INT NOT NULL AUTO_INCREMENT,
  `nombrePersonal` VARCHAR(45) NOT NULL,
  `apel_pat` VARCHAR(45) NOT NULL,
  `apel_mat` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `rut_personal` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `sueldo_personal` INT NOT NULL,
  `Turno_id_turno` INT NOT NULL,
  `Cargo_idCargo` INT NOT NULL,
  PRIMARY KEY (`idPersonal`, `Turno_id_turno`, `Cargo_idCargo`),
  INDEX `fk_Personal_Turno_idx` (`Turno_id_turno` ASC),
  INDEX `fk_Personal_Cargo1_idx` (`Cargo_idCargo` ASC),
  CONSTRAINT `fk_Personal_Turno`
    FOREIGN KEY (`Turno_id_turno`)
    REFERENCES `FastFoodBD`.`Turno` (`id_turno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Personal_Cargo1`
    FOREIGN KEY (`Cargo_idCargo`)
    REFERENCES `FastFoodBD`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FastFoodBD`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FastFoodBD`.`Venta` (
  `idVenta` INT NOT NULL AUTO_INCREMENT,
  `detalle_boleta` VARCHAR(45) NOT NULL,
  `sistema_compra` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVenta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FastFoodBD`.`Boleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FastFoodBD`.`Boleta` (
  `id_boleta` INT NOT NULL AUTO_INCREMENT,
  `detalle_boleta` VARCHAR(45) NOT NULL,
  `Venta_idVenta` INT NOT NULL,
  PRIMARY KEY (`id_boleta`),
  INDEX `fk_Boleta_Venta1_idx` (`Venta_idVenta` ASC),
  CONSTRAINT `fk_Boleta_Venta1`
    FOREIGN KEY (`Venta_idVenta`)
    REFERENCES `FastFoodBD`.`Venta` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FastFoodBD`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FastFoodBD`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `nombre_pedido` VARCHAR(45) NOT NULL,
  `descripcion_pedido` VARCHAR(45) NOT NULL,
  `Venta_idVenta` INT NOT NULL,
  `Personal_idPersonal` INT NOT NULL,
  `Personal_Turno_id_turno` INT NOT NULL,
  PRIMARY KEY (`idPedido`, `nombre_pedido`, `Personal_idPersonal`, `Personal_Turno_id_turno`),
  INDEX `fk_Pedido_Venta1_idx` (`Venta_idVenta` ASC),
  INDEX `fk_Pedido_Personal1_idx` (`Personal_idPersonal` ASC, `Personal_Turno_id_turno` ASC),
  CONSTRAINT `fk_Pedido_Venta1`
    FOREIGN KEY (`Venta_idVenta`)
    REFERENCES `FastFoodBD`.`Venta` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Personal1`
    FOREIGN KEY (`Personal_idPersonal` , `Personal_Turno_id_turno`)
    REFERENCES `FastFoodBD`.`Personal` (`idPersonal` , `Turno_id_turno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FastFoodBD`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FastFoodBD`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nombre_producto` VARCHAR(45) NOT NULL,
  `descripcion_producto` VARCHAR(45) NOT NULL,
  `precio_producto` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Pedido_nombre_pedido` VARCHAR(45) NOT NULL,
  `Pedido_Personal_idPersonal` INT NOT NULL,
  `Pedido_Personal_Turno_id_turno` INT NOT NULL,
  PRIMARY KEY (`idProducto`, `Pedido_idPedido`, `Pedido_nombre_pedido`, `Pedido_Personal_idPersonal`, `Pedido_Personal_Turno_id_turno`),
  INDEX `fk_Producto_Pedido1_idx` (`Pedido_idPedido` ASC, `Pedido_nombre_pedido` ASC, `Pedido_Personal_idPersonal` ASC, `Pedido_Personal_Turno_id_turno` ASC),
  CONSTRAINT `fk_Producto_Pedido1`
    FOREIGN KEY (`Pedido_idPedido` , `Pedido_nombre_pedido` , `Pedido_Personal_idPersonal` , `Pedido_Personal_Turno_id_turno`)
    REFERENCES `FastFoodBD`.`Pedido` (`idPedido` , `nombre_pedido` , `Personal_idPersonal` , `Personal_Turno_id_turno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FastFoodBD`.`adm_publicidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FastFoodBD`.`adm_publicidad` (
  `id_publicidad` INT NOT NULL AUTO_INCREMENT,
  `nombre_publicidad` VARCHAR(45) NOT NULL,
  `descripcion_publicacion` VARCHAR(45) NOT NULL,
  `tiempo_duracion` VARCHAR(45) NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  `Producto_Pedido_idPedido` INT NOT NULL,
  `Producto_Pedido_nombre_pedido` VARCHAR(45) NOT NULL,
  `Producto_Pedido_Personal_idPersonal` INT NOT NULL,
  `Producto_Pedido_Personal_Turno_id_turno` INT NOT NULL,
  PRIMARY KEY (`id_publicidad`, `Producto_idProducto`, `Producto_Pedido_idPedido`, `Producto_Pedido_nombre_pedido`, `Producto_Pedido_Personal_idPersonal`, `Producto_Pedido_Personal_Turno_id_turno`),
  INDEX `fk_adm_publicidad_Producto1_idx` (`Producto_idProducto` ASC, `Producto_Pedido_idPedido` ASC, `Producto_Pedido_nombre_pedido` ASC, `Producto_Pedido_Personal_idPersonal` ASC, `Producto_Pedido_Personal_Turno_id_turno` ASC),
  CONSTRAINT `fk_adm_publicidad_Producto1`
    FOREIGN KEY (`Producto_idProducto` , `Producto_Pedido_idPedido` , `Producto_Pedido_nombre_pedido` , `Producto_Pedido_Personal_idPersonal` , `Producto_Pedido_Personal_Turno_id_turno`)
    REFERENCES `FastFoodBD`.`Producto` (`idProducto` , `Pedido_idPedido` , `Pedido_nombre_pedido` , `Pedido_Personal_idPersonal` , `Pedido_Personal_Turno_id_turno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
